% Create a sample range gate

% generate impulse return for this target
    gateImpulse = gen_pd_impulse(...
        gateImpulse,...
        mod(tgtRanges(gateSignal),0.5*3e8/PRF),...
        PRF,...
        Ts,...
        1,...
        0,...
        0,...
        0);
gateSamples = conv(gateImpulse,ones(1,length(txWaveform)),'same');