function cm = colormap_zerowhite(N,posColor,negColor)


poscm = [...
    linspace(posColor(1),1,floor(N/2)).' ...
    linspace(posColor(2),1,floor(N/2)).' ...
    linspace(posColor(3),1,floor(N/2)).'];

negcm = [...
    linspace(1,negColor(1),floor(N/2)).' ...
    linspace(1,negColor(2),floor(N/2)).' ...
    linspace(1,negColor(3),floor(N/2)).'];

cm = [poscm; negcm];
cm = cm(end:-1:1,:);


end