close all;
clear all;
clc;
addpath(['I:\MATLAB\Printing']);
refLat = 0.0;
refLon = 0.0;

refECEF=convertGeodeticWGS84LatLonAltToECEF( ...
    refLat, ...
    refLon, ...
    0);


lonArray = linspace(refLon,refLon+200/60,1000);

lineECEF=convertGeodeticWGS84LatLonAltToECEF( ...
    0*lonArray' + refLat, ...
    lonArray', ...
    0*lonArray');

distance_m = [0;cumsum(sqrt(sum(diff(lineECEF).^2,2)))];

ecef_arc_wgs84_LLA=convertECEF_toTopocentricENU_GeodeticNormal( ...
    refECEF(1), ...
    refECEF(2), ...
    refECEF(3), ...
    refLat, ...
    refLon, ...
    lineECEF(:,1), ...
    lineECEF(:,2), ...
    lineECEF(:,3) );

figure(1);
plot(distance_m,ecef_arc_wgs84_LLA(:,3));
grid on;
xlabel('Arclength (m)');
ylabel('Altitude (m)');
title('Altitude Above WGS84 Ellipsoid');
add_print_callbacks;