function mmpolar_mod(azw,rcsw,minMaxShowForce)
rcspad = 5.0;
rcsspace = 5;
if(rcspad ~= 0)
    minrcsplot = round(min(rcsw)/rcspad)*rcspad - rcspad;
    maxrcsplot = round(max(rcsw)/rcspad)*rcspad + rcspad;
end
if( nargin > 2 )
    minrcsplot = minMaxShowForce(1);
    maxrcsplot = minMaxShowForce(2);
end

mmpolar( ...
    azw, rcsw, ...
    'Style','compass', ...
    'FontSize',10,...
    'RGridLineWidth',.5, ...
    'ThetaGridLineWidth',.5, ...
    'RTickAngle',15,...
    'RLimit',[minrcsplot maxrcsplot], ...
    'RTickValue',[minrcsplot:rcsspace:maxrcsplot], ...
    'RTickOffset',0,...
    'RTickLabelValign','top',...
    'TTickValue',[0:30:360], ...
    'TTickLabelVisible','on');
try
    set(get(gcaq,'Children'),'LineWidth',2);
catch
end